title: error404
email: p.l.edwards@leeds.ac.uk
description: >-
  Error 404 was a commission from e-2 for a project they were doing
  called Containership where they were asking artists who weren't digital
  artists. I'd never been on the web before, so the project was partly
  about a naïve navigation of cyber space and I tried to treat the internet
  as the real world, a physical space. I started surfing by taking some
  addresses from the bookmarks on a public library computer, random 
  starting points in cyberspace, and I just let one website lead me 
  to another. I worked with Pete Edwards to compose an animation of all 
  these different fragments to tell this story. The piece is a 20 minute 
  duration 'composition', and isn't interactive; the pop up and moving 
  windows fill up each viewer's desktop, rendering the viewer more passive 
  than usual. There is a central text that types out the main story letter 
  by letter , and the other images and texts pop onto the screen and move 
  around, seemingly taking over the desktop. I made a diagram/drawing to 
  map out the composition for Pete and that has been shown in Amsterdam.
  The website was launched at the Lux in London.
environment: development
url: "https://error404.bjorsq.net"
baseurl: ""
destination: _site/
host: "localhost"
google_analytics: ""
lang: "en"
dc:
  creator: "Anna Best"
  dateCreated: "2000-01-01"
  dateModified: "2023-10-27"
  publisher: "Anna Best"
  types:
    - "InteractiveResource"
  subjects:
    - "Digital Art"
sass:
  style: compressed
exclude:
  - package*
  - Gemfile*
  - README.md
  - public
  - node_modules